import type { Company, Employer } from "../types/employer";
import type { Job, JobApplication } from "../types/job";
import type { Student } from "../types/student";

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "TechCorp",
    industry: "Technology",
    description:
      "Leading technology solutions provider specializing in cloud computing and AI.",
    website: "https://techcorp.com",
    logoUrl:
      "https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    companySize: "201-500",
    foundedYear: 2010,
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "comp-2",
    name: "FinanceInc",
    industry: "Finance",
    description: "Financial services and investment banking solutions.",
    website: "https://financeinc.com",
    logoUrl:
      "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    city: "New York",
    state: "NY",
    country: "USA",
    companySize: "501-1000",
    foundedYear: 2005,
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "comp-3",
    name: "HealthCare Ltd",
    industry: "Healthcare",
    description: "Healthcare technology and digital health solutions.",
    website: "https://healthcare-ltd.com",
    logoUrl:
      "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    city: "Boston",
    state: "MA",
    country: "USA",
    companySize: "51-200",
    foundedYear: 2015,
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockEmployers: Employer[] = [
  {
    id: "emp-1",
    userId: "user-emp-1",
    companyId: "comp-1",
    name: "Sarah Johnson",
    email: "hr@techcorp.com",
    position: "HR Manager",
    phone: "+1-555-0101",
    company: mockCompanies[0],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-2",
    userId: "user-emp-2",
    companyId: "comp-2",
    name: "Michael Chen",
    email: "careers@financeinc.com",
    position: "Talent Acquisition Lead",
    phone: "+1-555-0102",
    company: mockCompanies[1],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-3",
    userId: "user-emp-3",
    companyId: "comp-3",
    name: "Emily Davis",
    email: "recruiting@healthcare-ltd.com",
    position: "Recruiting Manager",
    phone: "+1-555-0103",
    company: mockCompanies[2],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Software Engineering Intern",
    company: "TechCorp",
    companyId: "comp-1",
    description:
      "Join our dynamic development team and work on cutting-edge web applications using React, Node.js, and cloud technologies. You'll collaborate with senior engineers on real projects that impact millions of users.",
    requirements: ["React", "JavaScript", "Node.js", "Git"],
    responsibilities: [
      "Develop and maintain web applications",
      "Collaborate with cross-functional teams",
      "Write clean, maintainable code",
      "Participate in code reviews",
    ],
    salary: {
      min: 25,
      max: 35,
      currency: "USD",
      period: "hourly",
    },
    location: "San Francisco, CA",
    type: "internship",
    experienceLevel: "entry",
    skills: ["React", "JavaScript", "Node.js", "Git"],
    postedDate: "2024-01-20T00:00:00Z",
    applicationDeadline: "2024-03-01T00:00:00Z",
    status: "active",
    employerId: "emp-1",
    viewCount: 245,
    applicationCount: 18,
    isRemote: false,
  },
  {
    id: "2",
    title: "Financial Analyst",
    company: "FinanceInc",
    companyId: "comp-2",
    description:
      "Analyze financial data, create reports, and support investment decisions. Perfect opportunity for finance students to gain real-world experience in investment banking.",
    requirements: ["Excel", "Financial Modeling", "SQL", "Python"],
    responsibilities: [
      "Perform financial analysis and modeling",
      "Prepare investment reports",
      "Support due diligence processes",
      "Maintain financial databases",
    ],
    salary: {
      min: 70000,
      max: 85000,
      currency: "USD",
      period: "yearly",
    },
    location: "New York, NY",
    type: "full-time",
    experienceLevel: "entry",
    skills: ["Excel", "Financial Modeling", "SQL", "Python"],
    postedDate: "2024-01-18T00:00:00Z",
    applicationDeadline: "2024-02-28T00:00:00Z",
    status: "active",
    employerId: "emp-2",
    viewCount: 189,
    applicationCount: 24,
    isRemote: false,
  },
  {
    id: "3",
    title: "UX Design Intern",
    company: "TechCorp",
    companyId: "comp-1",
    description:
      "Work with our design team to create intuitive user experiences for our mobile and web applications. Learn from experienced designers and contribute to real projects.",
    requirements: [
      "Figma",
      "Adobe Creative Suite",
      "User Research",
      "Prototyping",
    ],
    responsibilities: [
      "Create wireframes and prototypes",
      "Conduct user research",
      "Design user interfaces",
      "Collaborate with development teams",
    ],
    salary: {
      min: 20,
      max: 28,
      currency: "USD",
      period: "hourly",
    },
    location: "San Francisco, CA",
    type: "internship",
    experienceLevel: "entry",
    skills: ["Figma", "Adobe Creative Suite", "User Research", "Prototyping"],
    postedDate: "2024-01-15T00:00:00Z",
    applicationDeadline: "2024-02-25T00:00:00Z",
    status: "active",
    employerId: "emp-1",
    viewCount: 156,
    applicationCount: 12,
    isRemote: true,
  },
];

export const mockStudents: Student[] = [
  {
    id: "student-1",
    userId: "user-student-1",
    name: "Alice Johnson",
    email: "alice.johnson@university.edu",
    phone: "+1-555-0201",
    city: "Boston",
    state: "MA",
    country: "USA",
    university: "University of Technology",
    major: "Computer Science",
    degreeLevel: "bachelor",
    graduationYear: 2024,
    currentYear: "senior",
    gpa: 3.8,
    bio: "Passionate computer science student with experience in full-stack development and machine learning.",
    portfolioUrl: "https://alicejohnson.dev",
    linkedinUrl: "https://linkedin.com/in/alicejohnson",
    githubUrl: "https://github.com/alicejohnson",
    cvUrl: "./careerlink.pdf",
    skills: [
      {
        id: "skill-1",
        skillId: "react",
        skillName: "React",
        category: "technical",
        proficiencyLevel: "advanced",
      },
      {
        id: "skill-2",
        skillId: "python",
        skillName: "Python",
        category: "technical",
        proficiencyLevel: "advanced",
      },
      {
        id: "skill-3",
        skillId: "ml",
        skillName: "Machine Learning",
        category: "technical",
        proficiencyLevel: "intermediate",
      },
    ],
    experiences: [
      {
        id: "exp-1",
        type: "internship",
        title: "Software Development Intern",
        organization: "StartupXYZ",
        description: "Developed React components and REST APIs",
        startDate: "2023-06-01",
        endDate: "2023-08-31",
        isCurrent: false,
        location: "Remote",
      },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "student-2",
    userId: "user-student-2",
    name: "Bob Chen",
    email: "bob.chen@university.edu",
    phone: "+1-555-0202",
    city: "Chicago",
    state: "IL",
    country: "USA",
    university: "State College",
    major: "Business Administration",
    degreeLevel: "bachelor",
    graduationYear: 2025,
    currentYear: "junior",
    gpa: 3.6,
    bio: "Business student with strong analytical skills and interest in project management.",
    linkedinUrl: "https://linkedin.com/in/bobchen",
    cvUrl: "./careerlink.pdf",
    skills: [
      {
        id: "skill-4",
        skillId: "excel",
        skillName: "Excel",
        category: "technical",
        proficiencyLevel: "advanced",
      },
      {
        id: "skill-5",
        skillId: "project-management",
        skillName: "Project Management",
        category: "soft",
        proficiencyLevel: "intermediate",
      },
    ],
    experiences: [
      {
        id: "exp-2",
        type: "work",
        title: "Business Analyst Intern",
        organization: "ConsultingCorp",
        description: "Analyzed business processes and created reports",
        startDate: "2023-09-01",
        endDate: "2023-12-31",
        isCurrent: false,
        location: "Chicago, IL",
      },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

export const mockApplications: JobApplication[] = [
  {
    id: "app-1",
    jobId: "job-1",
    studentId: "student-1",
    coverLetter:
      "I am very interested in this software engineering internship position...",
    status: "reviewing",
    appliedAt: "2024-01-22T10:30:00Z",
    updatedAt: "2024-01-23T14:20:00Z",
    reviewedAt: "2024-01-23T14:20:00Z",
  },
  {
    id: "app-2",
    jobId: "job-2",
    studentId: "student-2",
    coverLetter:
      "My background in business administration makes me a perfect fit...",
    status: "interview_scheduled",
    appliedAt: "2024-01-20T09:15:00Z",
    updatedAt: "2024-01-24T11:00:00Z",
    reviewedAt: "2024-01-24T11:00:00Z",
  },
];

export const mockSkills = [
  { id: "react", name: "React", category: "technical" },
  { id: "javascript", name: "JavaScript", category: "technical" },
  { id: "python", name: "Python", category: "technical" },
  { id: "nodejs", name: "Node.js", category: "technical" },
  { id: "sql", name: "SQL", category: "technical" },
  { id: "excel", name: "Excel", category: "technical" },
  { id: "figma", name: "Figma", category: "technical" },
  { id: "project-management", name: "Project Management", category: "soft" },
  { id: "communication", name: "Communication", category: "soft" },
  { id: "leadership", name: "Leadership", category: "soft" },
];
